const a = 'Anxious'
const c = 'Cotton Mouth'
const d = 'Dizzy'
const h = 'Headache'
const r = 'Red Eyes'
const p = 'Paranoid'

export const data = [
    {
        name: 'Lemon Cherry Gelato',
        effects: ['tingly', 'relaxed', 'giggly'],
        negEffects: [a, h, d],
        flavors: ['Lemon', ' Citrus', ' Berry'],
        thc: 20,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://images.leafly.com/flower-images/defaults/generic/strain-40.png?auto=compress%2Cformat&w=215&dpr=1',
    },
    {
        name: 'Blue Dream',
        effects: ['creative', 'euphoric', 'happy'],
        negEffects: [c, r, d],
        flavors: ['Berry', ' Blueberry', ' Sweet'],
        thc: 21,
        hasCbd: true,
        type: 'Hybrid',
        medical: 'Stress',
        image: 'https://images.leafly.com/flower-images/blue-dream.png?auto=compress%2Cformat&w=215&dpr=1',
    },
    {
        name: 'Wedding Cake',
        effects: ['relaxed', 'aroused', 'hungry'],
        negEffects: [a, c, d],
        flavors: ['Vanilla', ' Pepper', ' Butter'],
        thc: 24,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
       image: 'https://leafly-public.imgix.net/strains/photos/m2y50HYRBu0dHY4JSdSx_wedding-cake_jman.jpg?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Permanent Marker',
        effects: ['tingly', 'relaxed', 'euphoric'],
        negEffects: [a, h, d],
        flavors: ['Ammonia', ' Chemical', ' Tobacco'],
        thc: 25,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
       image: 'https://leafly-public.imgix.net/strains/photos/aMsjhhOYQualXxE7TqQt_LEF-STOY2023-StrainPDP-1080x1080.png?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'GG4',
        effects: ['relaxed', 'sleepy', 'hungry'],
        negEffects: [c, r, a],
        flavors: ['Pungent', ' Earthy', ' Pine'],
        thc: 20,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Stress',
       image: 'https://images.leafly.com/flower-images/gg-4.jpg?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Super Boof',
        effects: ['giggly', 'euphoric', 'focused'],
        negEffects: [d, c, h],
        flavors: ['Grapefruit', ' Citrus', ' Orange'],
        thc: 26,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
       image: 'https://leafly-public.imgix.net/strains/photos/eK2NOtifQeuwvKBNqGuV_Screenshot%202024-12-11%20at%209.22.55%20AM.png?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'Grandaddy Purple',
        effects: ['sleepy', 'relaxed', 'hungry'],
        negEffects: [c, r, d],
        flavors: ['Grape', ' Berry', ' Violet'],
        thc: 17,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Stress',
       image: 'https://images.leafly.com/flower-images/granddaddy-purple.png?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Ice Cream Cake',
        effects: ['sleepy', 'relaxed', 'hungry'],
        negEffects: [c, a, d],
        flavors: ['Vanilla', ' Butter', ' Pepper'],
        thc: 22,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
       image: 'https://images.leafly.com/flower-images/defaults/generic/strain-32.png?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Sour Diesel',
        effects: ['energetic', 'talkative', 'uplifted'],
        negEffects: [c, r, p],
        flavors: ['Diesel', ' Chemical', ' Skunk'],
        thc: 19,
        hasCbd: false,
        type: 'Indica',
        medical: 'Stress',
       image: 'https://leafly-public.imgix.net/strains/photos/5SPDG4T4TcSO8PgLgWHO_SourDiesel_AdobeStock_171888473.jpg?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Runtz',
        effects: ['talkative', 'relaxed', 'giggly'],
        negEffects: [a, c, d],
        flavors: ['Apricot', ' Sweet', ' Fruity'],
        thc: 21,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
       image: 'https://images.leafly.com/flower-images/runtz-nug-image.jpg?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Gelato',
        effects: ['relaxed', 'aroused', 'euphoric'],
        negEffects: [c, a, r],
        flavors: ['Sweet', ' Flowery', ' Pepper'],
        thc: 21,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://images.leafly.com/flower-images/gelato.jpg?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Cereal Milk',
        effects: ['aroused', 'relaxed', 'giggly'],
        negEffects: [h, a, c],
        flavors: ['Butter', ' Vanilla', ' Sweet'],
        thc: 25,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://leafly-public.imgix.net/strains/photos/fRrra4kRgiCHsreJvZDw_cereal%20milk%20nug%20small.jpg?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'White Widow',
        effects: ['euphoric', 'uplifted', 'talkative'],
        negEffects: [c, r, d],
        flavors: ['Woody', ' Earthy', ' Flowery'],
        thc: 15,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Stress',
        image: 'https://images.leafly.com/flower-images/white-widow.png?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'OG Kush',
        effects: ['hungry', 'relaxed', 'sleepy'],
        negEffects: [c, r, d],
        flavors: ['Woody', ' Pine', ' Earthy'],
        thc: 25,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Stress',
        image: 'https://images.leafly.com/flower-images/og-kush.png?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Girl Scout Cookies',
        effects: ['relaxed', 'hungry', 'happy'],
        negEffects: [c, r, a],
        flavors: ['Mint', ' Sweet', ' Earthy'],
        thc: 25,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Stress',
        image: 'https://images.leafly.com/flower-images/gsc.png?auto=compress%2Cformat&w=215&dpr=1',
        
    },
        {
        name: 'Northern Lights',
        effects: ['sleepy', 'relaxed', 'hungry'],
        negEffects: [c, r, d],
        flavors: ['Pine', ' Earthy', ' Woody'],
        thc: 18,
        hasCbd: false,
        type: 'Indica',
        medical: 'Stress',
        image: 'https://images.leafly.com/flower-images/northern-lights.png?auto=compress%2Cformat&w=350&dpr=1',
        
    },
        {
        name: 'Pineapple Express',
        effects: ['happy', 'giggly', 'energetic'],
        negEffects: [c, a, r],
        flavors: ['Pineapple', ' Tropical', ' Citrus'],
        thc: 20,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Stress & Depression',
        image: 'https://images.leafly.com/flower-images/pineapple-express.png?auto=compress%2Cformat&w=350&dpr=1',
       
    },
    {
        name: 'Biscotti',
        effects: ['tingly', 'relaxed', 'euphoric'],
        negEffects: [a, h, c],
        flavors: ['Butter', ' Honey', ' Vanilla'],
        thc: 20,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://images.leafly.com/flower-images/defaults/generic/strain-29.png?auto=compress%2Cformat&w=350&dpr=1',
    },
    {
        name: 'Jack Herer',
        effects: ['focused', 'energetic', 'creative'],
        negEffects: [c, r, a],
        flavors: ['Pine', ' Woody', ' Earthy'],
        thc: 18,
        hasCbd: false,
        type: 'Sativa',
        medical: 'Stress & Depression',
        image: 'https://images.leafly.com/flower-images/jack-herer.jpg?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'GMO Cookies',
        effects: ['relaxed', 'sleepy', 'euphoric'],
        negEffects: [a, c, d],
        flavors: ['Chemical', ' Pepper', ' Pungent'],
        thc: 28,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety & Pain',
        image: 'https://images.leafly.com/flower-images/defaults/red-orange-amber/strain-2.png?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Sherbert',
        effects: ['relaxed', 'tingly', 'happy'],
        negEffects: [c, a, r],
        flavors: ['Citrus', ' Sweet', ' Tropical'],
        thc: 18,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Stress, Anxiety, & Depression',
        image: 'https://images.leafly.com/flower-images/sunset-sherbert.jpg?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Gary Payton',
        effects: ['giggly', 'relaxed', 'euphoric'],
        negEffects: [a, c, p],
        flavors: ['Apricot', ' Pepper', ' Lavender'],
        thc: 22,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://leafly-public.imgix.net/strains/photos/JNC0ZSxRVGZyjFszg0po_GaryPayton%20(1).jpg?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'Gumbo',
        effects: ['sleepy', 'relaxed', 'hungry'],
        negEffects: [c, r, d],
        flavors: ['Ammonia', ' Pine', ' Sage'],
        thc: 19,
        hasCbd: false,
        type: 'Indica',
        medical: 'Pain & Stress',
        image: 'https://images.leafly.com/flower-images/defaults/purple/strain-5.png?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Apple Fritter',
        effects: ['tingly', 'relaxed', 'giggly'],
        negEffects: [d, c, h],
        flavors: ['Apple', ' Butter', ' Cheese'],
        thc: 24,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://leafly-public.imgix.net/strains/photos/ziw0L3SZSIyM6uiLup73_AppleFritter%20(1).jpg?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Oreoz',
        effects: ['relaxed', 'hungry', 'tingly'],
        negEffects: [h, a, c],
        flavors: ['Tobacco', ' Vanilla', ' Coffee'],
        thc: 20,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety & Depression',
        image: 'https://images.leafly.com/flower-images/defaults/generic/strain-40.png?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Durban Poison',
        effects: ['focused', 'energetic', 'uplifted'],
        negEffects: [a, c, r],
        flavors: ['Pine', ' Earthy', ' Sage'],
        thc: 19,
        hasCbd: false,
        type: 'Sativa',
        medical: 'Stress',
        image: 'https://images.leafly.com/flower-images/durban-poison.jpg?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'Pink Runtz',
        effects: ['talkative', 'tingly', 'giggly'],
        negEffects: [h, c, a],
        flavors: ['Rose', ' Flower', ' Sweet'],
        thc: 25,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://images.leafly.com/flower-images/defaults/short-dense-heavy/strain-15.png?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Purple Punch',
        effects: ['sleepy', 'relaxed', 'hungry'],
        negEffects: [c, r, d],
        flavors: ['Grape', ' Plum', ' Berry'],
        thc: 18,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety & Nausea',
        image: 'https://images.leafly.com/flower-images/purple-punch-fixed.jpg?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'The Original Z',
        effects: ['relaxed', 'sleepy', 'hungry'],
        negEffects: [h, c, r],
        flavors: ['Grapefruit', ' Grape', ' Berry'],
        thc: 20,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Stress',
        image: 'https://leafly-public.imgix.net/strains/photos/6VF5EvUTjqZPKFVOQAAY_Zkittlez.jpg?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Mac 1',
        effects: ['uplifted', 'euphoric', 'relaxed'],
        negEffects: [a, d, c],
        flavors: ['Butter', ' Citrus', ' Vanilla'],
        thc: 22,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://leafly-public.imgix.net/strains/photos/X6WMoxxxTSFF7t7tOqgO_MAC.jpg?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'RS11',
        effects: ['focused', 'giggly', 'relaxed'],
        negEffects: [h, c, a],
        flavors: ['Apricot', ' Peach', ' Citrus'],
        thc: 24,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety & Pain',
        image: 'https://images.leafly.com/flower-images/defaults/generic/strain-27.png?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Jealousy',
        effects: ['giggly', 'relaxed', 'talkative'],
        negEffects: [a, h, c],
        flavors: ['Pepper', ' Plum', ' Apricot'],
        thc: 25,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://leafly-public.imgix.net/strains/photos/lfgn9PfQcS7RL18QA4te_Jealousy-PDP-Image-v1%20copy.jpeg?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'White Runtz',
        effects: ['tingly', 'relaxed', 'euphoric'],
        negEffects: [c, a, h],
        flavors: ['Peach', ' Vanilla', ' Flowery'],
        thc: 18,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://images.leafly.com/flower-images/defaults/generic/strain-9.png?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Dosidos',
        effects: ['relaxed', 'sleepy', 'tingly'],
        negEffects: [d, c, r],
        flavors: ['Flowery', ' Pepper', ' Earthy'],
        thc: 20,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://leafly-public.imgix.net/jdRI25LqQM6Wavphys2K_nug-dosidos-v1.jpg?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Zoap',
        effects: ['giggly', 'relaxed', 'euphoric'],
        negEffects: [c, r, d],
        flavors: ['Apricot', ' Chemical', ' Apple'],
        thc: 21,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://leafly-public.imgix.net/strains/photos/QEJXLkqjSWufdzJEi0PR_Deo%20Farms%20Zoap%20Photo%20by%20David%20Downs%20Leafly%202%20smaller.jpg?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Strawberry Cough',
        effects: ['uplifted', 'energetic', 'happy'],
        negEffects: [c, r, d],
        flavors: ['Strawberry', ' Sweet', ' Berry'],
        thc: 19,
        hasCbd: false,
        type: 'Sativa',
        medical: 'Stress & Depression',
        image: 'https://images.leafly.com/flower-images/strawberry-cough.png?auto=compress%2Cformat&w=215&dpr=1',
    },
    {
        name: 'Gelato #41',
        effects: ['relaxed', 'aroused', 'tingly'],
        negEffects: [a, p, c],
        flavors: ['Lavender', ' Pepper', ' Flowery'],
        thc: 21,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://images.leafly.com/flower-images/defaults/purple/strain-8.png?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'Green Crack',
        effects: ['energetic', 'focused', 'talkative'],
        negEffects: [a, c, p],
        flavors: ['Citrus', ' Mango', ' Earthy'],
        thc: 17,
        hasCbd: false,
        type: 'Sativa',
        medical: 'Stress',
        image: 'https://images.leafly.com/flower-images/green-crack.png?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'Mimosa',
        effects: ['focused', 'energetic', 'uplifted'],
        negEffects: [a, c, r],
        flavors: ['Citrus', ' Orange', ' Grapefruit'],
        thc: 19,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety & Depression',
        image: 'https://leafly-public.imgix.net/strains/photos/sE4UZNIUQbSxoqEEk0E1_Mimosa.png?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'Amnesia Haze',
        effects: ['giggly', 'euphoric', 'talkative'],
        negEffects: [p, d, c],
        flavors: ['Citrus', ' Lemon', ' Lime'],
        thc: 19,
        hasCbd: false,
        type: 'Sativa',
        medical: 'Stress & Depression',
        image: 'https://images.leafly.com/flower-images/defaults/generic/strain-25.png?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'Cherry Pie',
        effects: ['relaxed', 'giggly', 'happy'],
        negEffects: [c, r, a],
        flavors: ['Tree Fruit', ' Berry', ' Sweet'],
        thc: 16,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Stress & Anxiety',
        image: 'https://images.leafly.com/flower-images/cherry-pie.jpg?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'Kush Mints',
        effects: ['aroused', 'relaxed', 'euphoric'],
        negEffects: [a, c, r],
        flavors: ['Menthol', ' Mint', ' Ammonia'],
        thc: 28,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://images.leafly.com/flower-images/defaults/generic/strain-17.png?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'Cap Junky',
        effects: ['giggly', 'tingly', 'relaxed'],
        negEffects: [a, d, c],
        flavors: ['Apricot', ' Apple', ' Menthol'],
        thc: 19,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://leafly-public.imgix.net/strains/photos/YewiQ2IoTQOG9h6saIVZ_LA%20Made%20-%20Cap%20Junky%20-%20cover%20-%20David%20Downs%20at%20leafly%20copy%20smol.jpg?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'Mochi',
        effects: ['sleepy', 'relaxed', 'hungry'],
        negEffects: [a, c, r],
        flavors: ['Menthol', ' Mint', ' Flowery'],
        thc: 23,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://images.leafly.com/flower-images/defaults/purple/strain-5.png?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'Super Lemon Haze',
        effects: ['energetic', 'focused', 'uplifted'],
        negEffects: [a, c, r],
        flavors: ['Lemon', ' Citrus', ' Lime'],
        thc: 19,
        hasCbd: false,
        type: 'Sativa',
        medical: 'Stress & Depression',
        image: 'https://leafly-public.imgix.net/strains/photos/QRio3lTnO1PsVFx8Sxw1_super-lemon-haze_jman.jpg?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'Maui Wowie',
        effects: ['energetic', 'uplifted', 'happy'],
        negEffects: [c, r, h],
        flavors: ['Tropical', ' Pineapple', ' Citrus'],
        thc: 19,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Stress & Anxiety',
        image: 'https://images.leafly.com/flower-images/defaults/generic/strain-18.png?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'Lemon Haze',
        effects: ['giggly', 'talkative', 'happy'],
        negEffects: [c, d, p],
        flavors: ['Lemon', ' Citrus', ' Lime'],
        thc: 19,
        hasCbd: false,
        type: 'Sativa',
        medical: 'Stress & Depression',
        image: 'https://images.leafly.com/flower-images/defaults/red-orange-amber/strain-4.png?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'Rainbow Belts',
        effects: ['relaxed', 'giggly', 'euphoric'],
        negEffects: [d, c, h],
        flavors: ['Tropical', ' Tree Fruit', ' Sweet'],
        thc: 20,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://images.leafly.com/flower-images/defaults/purple/strain-3.png?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'White Truffle',
        effects: ['tingly', 'aroused', 'relaxed'],
        negEffects: [h, c, d],
        flavors: ['Butter', ' Nutty', ' Chestnut'],
        thc: 24,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://images.leafly.com/flower-images/defaults/frosty/strain-2.png?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'Gelonade',
        effects: ['energetic', 'focused', 'talkative'],
        negEffects: [h, c, a],
        flavors: ['Ammonia', ' Lemon', ' Pepper'],
        thc: 22,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://images.leafly.com/flower-images/defaults/generic/strain-16.png?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'Slurricane',
        effects: ['sleepy', 'relaxed', 'hungry'],
        negEffects: [h, c, d],
        flavors: ['Butter', ' Nutty', ' Chestnut'],
        thc: 21,
        hasCbd: false,
        type: 'Indica',
        medical: 'Anxiety',
        image: 'https://leafly-public.imgix.net/strains/photos/MPWPStPKT0mQMfMPq3fX_Slurricane.jpg?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'Chemdawg',
        effects: ['euphoric', 'relaxed', 'tingly'],
        negEffects: [c, r, d],
        flavors: ['Chemical', ' Diesel', ' Pungent'],
        thc: 18,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Stress, Anxiety, & Pain',
        image: 'https://images.leafly.com/flower-images/defaults/generic/strain-1.png?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'Cheetah Piss',
        effects: ['aroused', 'giggly', 'focused'],
        negEffects: [a, p, c],
        flavors: ['Ammonia', ' Menthol', ' Skunk'],
        thc: 25,
        hasCbd: false,
         type: 'Hybrid',
        medical: 'Anxiety',
        image: 'https://images.leafly.com/flower-images/defaults/generic/strain-10.png?auto=compress%2Cformat&w=350&dpr=1',
    },
        {
        name: 'AK-47',
        effects: ['hungry', 'happy', 'talkative'],
        negEffects: [c, r, d],
        flavors: ['Skunk', ' Tobacco', ' Earthy'],
        thc: 19,
        hasCbd: false,
        type: 'Hybrid',
        medical: 'Stress',
        image: 'https://images.leafly.com/flower-images/defaults/generic/strain-1.png?auto=compress%2Cformat&w=350&dpr=1',
    },
    {
        name: 'Blueberry',
        effects: ['sleepy', 'relaxed', 'happy'],
        negEffects: [c, r, d], 
        flavors: ['Blueberry', ' Berry', ' Sweet'], 
        thc: 17,
        hasCbd: false, 
        type: 'Indica',
        medical: 'Stress & Pain',
        image: 'https://images.leafly.com/flower-images/blueberry.jpg?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Purple Haze',
        effects: ['creative', 'euphoric', 'giggly'],
        negEffects: [d, c, r], 
        flavors: ['Lavender', ' Flowery', ' Violet'], 
        thc: 16,
        hasCbd: false, 
        type: 'Sativa',
        medical: 'Stress & Anxiety',
        image: 'https://images.leafly.com/flower-images/defaults/purple/strain-10.png?auto=compress%2Cformat&w=215&dpr=1',
    },
        {
        name: 'Bubba Kush',
        effects: ['sleepy', 'relaxed', 'hungry'],
        negEffects: [c, r, d], 
        flavors: ['Coffee', ' Earthy', ' Pungent'], 
        thc: 17,
        hasCbd: false, 
        type: 'Indica',
        medical: 'Stress, Pain, & Insomnia' ,
        image: 'https://images.leafly.com/flower-images/bubba-kush.png?auto=compress%2Cformat&w=215&dpr=1',
    },
]